profiles:
  app:
    projectPath: Drukarnik.xcodeproj
    scheme: Drukarnik
    simulatorName: iPhone 17 Pro
    simulatorId: 5DA134F0-EFBB-400B-850E-8429E2228EB8
    simulatorPlatform: iOS Simulator
    useLatestOS: false
  tests:
    projectPath: Drukarnik.xcodeproj
    scheme: Drukarnik
    testTarget: KeyboardTests
    simulatorName: iPhone 17 Pro
    simulatorId: 5DA134F0-EFBB-400B-850E-8429E2228EB8
    simulatorPlatform: iOS Simulator
    useLatestOS: false
